id: PFFEAFDE8
initial_creation_type: input
source_metadata:
  title: Dudjom Rinpoche Series
  language: en
  description: 'We present the following texts by Kyabje Dudjom Rinpoche Jikdral Yeshe
    Dorje (bdud ''joms ''jigs bral ye shes rdo rje, 1904–1987), the renowned yogi
    and scholar and first appointed head of the Nyingma school in exile:'
  volume:
    a0af543ac6f24b1c98ad29f797ac8965:
      title: The Mirror Clearly Showing What to Adopt and Abandon
      parent: Advice
    cc3d0140ab524749be494abf7870b0f5:
      title: The Concise Benefits of the Festival of the Tenth Day
      parent: Benefits
    9ee83b2abe94446eac5463dc44e472f4:
      title: 'The Light of Primordial Wisdom: An Instruction Manual for the Primordially
        Pure Perfection Stage of the Powerful & Wrathful Dorje Drolö, Conqueror of
        Demons'
      parent: Commentaries
    2208b32e338f4ebaaf3e6552f09ce617:
      title: The Ornament of Padmasambhava’s Enlightened Vision
      parent: Commentaries
    2331de853fa541ef98dd54a8051a77f9:
      title: Concise Consecration
      parent: Consecration
    6a0feb7b81514109af81c37b46bdab93:
      title: A Brief Petitionary Offering to the Mātṛkā Pukkasī, Local Protectress
        of the Jarung Kashor Stūpa
      parent: Dharma Protectors
    7dd98d71ac3341ab9eeb26cdb0e506c9:
      title: Dzogchen Aspiration Prayer
      parent: Dzogchen
    1f050c256abb418091c54763f961d3a1:
      title: 'Spontaneous Song of the Genuine Nature: A Prayer of Calling the Guru
        from Afar'
      parent: Dzogchen
    51b1252adefd4c3997f270b137eb86f9:
      title: Summary of Striking the Vital Point in Three Statements
      parent: Dzogchen
    48494c826f7147e8977233aab33b9613:
      title: 'A Joyful Chariot for the Fortunate: An Aspiration to Travel to the Copper-Coloured
        Mountain of Glory'
      parent: Guru Rinpoche Prayers
    a88ca935b0a1479e96341410b0fc7766:
      title: A Prayer of Aspiration for the Copper-Coloured Mountain of Glory
      parent: Guru Rinpoche Prayers
    d6919dca4209450297144101b2c5bf1a:
      title: A Short Prayer to the Abbot, the Master and the King
      parent: Guru Rinpoche Prayers
    5ad23cb2ec2744219c546bb4ca060f71:
      title: 'Drumbeat of the Deathless Vajra: A Fervent Invocation and Prayer'
      parent: Guru Rinpoche Prayers
    d6a101e1e342425bbbcc8f05795dbc24:
      title: The Prayer to Guru Rinpoche that Swiftly Removes Obstacles and Fulfills
        All Wishes
      parent: Guru Rinpoche Prayers
    a48d06fb76604c078bd06653bb1a59be:
      title: A Concise Lineage Prayer
      parent: Lineage Prayers
    d00cd98403134eea84df62395b3cb805:
      title: Prayer for the Long Life Dodrupchen Rinpoche
      parent: Long Life Prayers
    4d478ef44b074f6c9bb9a81ad46e95b5:
      title: Prayer for the Long Life of Chökyi Nyima Rinpoche
      parent: Long Life Prayers
    8178b41081704f43bac7db5e422238c0:
      title: Prayer for the Long Life of Dzogchen Rinpoche
      parent: Long Life Prayers
    052d2cd28b4d4732885b7f8f7903e5df:
      title: Prayer for the Long Life of His Holiness the Dalai Lama
      parent: Long Life Prayers
    5efcc3dd71d544d9a0bb3e6dfda1475a:
      title: 'The Drumbeat of Immortality: A Prayer for the Long Life of the Great
        Tertön Dudjom Jigdral Yeshe Dorje'
      parent: Long Life Prayers
    4039a663122c46928004a3ed9d1ff0be:
      title: A Concise Recitation of the Preliminary Practice according to the New
        Treasure of Dudjom
      parent: Ngöndro
    3d838f7379244990b2dbc3dd2070ff7e:
      title: Brief Notes on the Visualization for the Concise Recitation of the Pure
        Vision Preliminary Practice
      parent: Ngöndro
    1c4a592bf5e844a78f0a53a10fd47e41:
      title: Brief Red Sur Offering
      parent: Offering
    a707c44cefe145f18360ee2d47a39ebc:
      title: Brief Sur Offering
      parent: Offering
    fddc9216ed20408883f31d6d49440c67:
      title: A Prayer to Recognize My Own Faults and Keep in Mind the Objects of Refuge
      parent: Prayers
    7f0f4972ca224f759311a5e10b2d3167:
      title: Essence and Embodiment of All the Buddhas
      parent: Prayers
    4050f9e293cc43939b57d871628e98a7:
      title: Prayer to the Three Great Stūpas of Kathmandu
      parent: Prayers
    f2c2f4e760d540a5b182c89a8320e42a:
      title: A Daily 'Hand-Clapping' Practice of Siṃhamukhā
      parent: Sādhanas
    664131ef62714feda9a7fef5a2f59e92:
      title: A Daily Long-Life Practice of Amitāyus
      parent: Sādhanas
    2b146107e04642b39784f4a3bb44a725:
      title: A Daily Practice of Lama Sangdü
      parent: Sādhanas
    1b8ab92d08884da183aaeda17bf039dd:
      title: A Daily Practice of Ucchuṣma
      parent: Sādhanas
    df918be74c53454eabf772308d2c52b1:
      title: Condensed Daily Practice of The Heart Essence of the Sublime Lady of
        Immortality
      parent: Sādhanas
    1be2c12ec8b34bfd836320a456180098:
      title: Daily Practice of Dorje Gotrab
      parent: Sādhanas
    d010b13c8baf40d9b2461332b3a2b73c:
      title: 'The Blazing Tower: A Daily Practice of Uṣṇīṣa-Sitātapatrā'
      parent: Sādhanas
    4c57a4c708be47509443060c389d18a2:
      title: 'The Concentrated Essence: A Sādhana of Yeshe Tsogyal'
      parent: Sādhanas
    e7b535d6f53e4f6cb22d8d9189d823a5:
      title: The Daily Practice of the Secret Sādhana of Dorje Drolö
      parent: Sādhanas
    8b64de0c421c4bd9af6516a9984e7fb7:
      title: The Essential Daily Practice of Vajrakīla
      parent: Sādhanas
    b52cc6cf869f4d598cce8b32a166c202:
      title: 'The Sublime Path to Immortality: The Quintessence of Profoundly Secret
        Pith Instructions on Attaining Vajra Longevity'
      parent: Sādhanas
    9e2427489f714f65b680ff601dc43beb:
      title: 'Divine Blue Water: A Contamination Purifying Smoke Offering by the Great
        Master Padmasambhava'
      parent: Sang Offering
    3cde4c86775d49e3bb2b4df1d57f0806:
      title: The Mountain Smoke Offering Arranged for Recitation
      parent: Sang Offering
    7363c999833a4fcf9ed9678331844e78:
      title: 'The Concentrated Essence: A Concise Practice of Healing and Purifying
        (Sojong) the Three Sets of Vows'
      parent: Sojong
    b534ee818cc049efb372cc50b6fd2172:
      title: Remainder Torma Offering for Seven-Line Prayer Guru Yoga
      parent: Tsok
    6fc4ee1ae1fb4b079d74ba76bf432484:
      title: The Brief Tsok Feast Offering Prayer from 'The Profound Path of the Ḍākinīs'
        Heart Drop'
      parent: Tsok
    b9a9a91b9ac94638910b82093bef91c4:
      title: A Daily Practice of Vajraṇakhī
      parent: Vajraṇakhī
created_at: '2022-02-28T23:10:30.047051'
last_modified_at: '2022-02-28T23:10:30.047057'
